project_id = "hlhzqotowrxnwezoheib"

[functions.paystack-webhook]
verify_jwt = false

[functions.flutterwave-webhook]
verify_jwt = false

[functions.create-virtual-account]
verify_jwt = true

[functions.update-profile]
verify_jwt = true

[functions.vtpass-purchase]
verify_jwt = true

[functions.get-wallet]
verify_jwt = true